### ISSUE TITLE
[QUESTION] removing outdated branches from styleguide

### ISSUE THREAD

**Issue by ashjtan** [square/maker#131] opened 2021-09-13 20:55 UTC
### Feature request

The ["WIP Branches" section](https://square.github.io/maker/) gets pretty lengthy as there are more and more branches that have been created. I noticed that there are some branches on that list that have since been deleted, including `card-component`, `text-button`, etc.

<img width="371" alt="Screen Shot 2021-09-13 at 1 54 48 PM" src="https://user-images.githubusercontent.com/20190589/133155028-02f51a35-6931-45a0-82c7-e884a3d3bb68.png">

- Can we remove the links for deployed styleguides of branches that have been deleted?
- Is there currently a process that removes outdated branch styleguides/links?
  - If so, can we update it to remove when the branch is merged into `master` or deleted?

### Why?

- Increases visibility of active WIP branches
- Removes stale info

**Comment by pretzelhammer** [comment] 2021-09-27 14:34
> Can we remove the links for deployed styleguides of branches that have been deleted?

Yes, although right now it's a manual process, it requires checking out the `deploys` branch of the repo and deleting the folders containing the stale/deleted branches and pushing a commit.

> Is there currently a process that removes outdated branch styleguides/links?

Not a process but a person, that person being me, or really anyone who's willing to do the instructions described above.

> If so, can we update it to remove when the branch is merged into master or deleted?

Yes, this should be possible, it would require writing a new github action (or possibly modifying an existing one) that basically does the same steps I outlined above.

**Comment by pretzelhammer** [comment] 2021-09-27 14:42
I'm gonna close this since it's a duplicate of this: https://github.com/square/maker/issues/45

**Closed by pretzelhammer** 2021-09-27 14:42 UTC
Labels: question, feature request, pending triage

**Comment by pretzelhammer** [comment] 2022-05-20 19:45
completed in this pr https://github.com/square/maker/pull/331
