### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by tatems** [square/maker#132] opened 2021-09-17 20:05 UTC

**Comment by landondurnan** [comment] 2021-09-17 20:18
Making a note here that the default Project -> Issue has a blank template. This issue will need to be fleshed out and perhaps we need a template specific to new components.

**Comment by pretzelhammer** [comment] 2021-09-27 14:35
@tatems if this issue is a duplicate of this https://github.com/square/maker/issues/134 then please close this issue, otherwise please update the issue description to describe how it is different, thanks.

**Closed** 2021-09-28 14:39 UTC
Labels: feature request
